[phases.setup]
aptPkgs = [
  "libxcb1",
  "libx11-6",
  "libx11-xcb1",
  "libgl1",
  "libglib2.0-0",
  "libxcb-render0",
  "libxcb-shape0",
  "libxcb-xfixes0"
]

[phases.build]
cmds = [
  "pip uninstall -y opencv-python",
  "pip install --force-reinstall opencv-python-headless"
]